---
- name: Install Docker on EC2
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: true
        state: started
