name: Provision and Configure EC2

on:
  push:
    branches:
      - main

jobs:
  provision:
    name: Terraform + Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./Terraform

      - name: Wait for EC2 to boot
        run: sleep 60

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      
